spring:
  application:
    name: od-cloud
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 3000

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection:
            timeout: 5000
            write-timeout: 5000
          ssl:
            enable: false

  datasource:
    url: ${RDB_HOST}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

service-constant:
  jwt:
    temp-token-ttl: 300000 # 5 min
    access-token-ttl: 1800000 # 30 min
    refresh-token-ttl: 7200000 # 2 hour
    secretKey: ${JWT_SECRET}

  google-oauth2:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/auth/google
    token-api: https://oauth2.googleapis.com
    user-info-api: https://www.googleapis.com

  redis-key:
    token: token::%s-%s
    group: group

  file-upload:
    base-path: /Users/od/IdeaProjects/od-cloud
  aes-secret-key: ${AES_SECRET}